services:
  mockoon:
    image: mockoon/cli:latest
    container_name: mockoon-challenge-itau
    ports:
      - "9090:9090"
    volumes:
      - ./mockon-data:/data:ro
    command: ["-d", "/data/bacen_mock.json", "-p", "9090"]
  mongodb:
    image: mongo:latest
    container_name: mongodb-challenge-itau
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
  localstack:
    image: localstack/localstack:latest
    container_name: sqs-challenge-itau
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DEBUG_SQS=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"